definitions:
  model.LogInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.LogInResponse:
    properties:
      message:
        type: string
      status:
        type: boolean
      userID:
        type: integer
    type: object
  model.PrivateDataResponse:
    properties:
      capsule:
        type: string
      cipher_text:
        type: string
      did:
        type: string
      user_id:
        type: integer
    type: object
  model.PublicDataResponse:
    properties:
      communities:
        type: string
      did:
        type: string
      focus_area:
        type: string
      user_id:
        type: integer
    type: object
  model.SignUpRequest:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  model.SignUpResponse:
    properties:
      message:
        type: string
      status:
        type: boolean
      userID:
        type: integer
    type: object
info:
  contact: {}
paths:
  /getAllAccessDatabyDID:
    get:
      consumes:
      - application/json
      description: Get rivate data that has been given access to a  DID
      parameters:
      - description: User's DID
        in: query
        name: did
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.PrivateDataResponse'
            type: array
      summary: Return user private data that has been given access to a  DID
  /getAllPrivateDataByDID:
    get:
      consumes:
      - application/json
      description: Get private data for a user by their DID
      parameters:
      - description: User's DID
        in: query
        name: did
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PrivateDataResponse'
      summary: Return user private data by DID
  /getAllPublicDataByDID:
    get:
      consumes:
      - application/json
      description: Get public data for a user by their DID
      parameters:
      - description: User's DID
        in: query
        name: did
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PublicDataResponse'
      summary: Return user public data by DID
  /login:
    post:
      consumes:
      - application/json
      description: This endpoint is used to authenticate existing user log in
      parameters:
      - description: enter email and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.LogInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LogInResponse'
      summary: Return user data
  /signup:
    post:
      consumes:
      - application/json
      description: This endpoint is used to when new user signs up
      parameters:
      - description: enter email and phone number
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SignUpResponse'
      summary: Return user data
swagger: "2.0"
